services:
  cache:
    image: redis:alpine
    ports:
      - "63791:6379"
    networks:
      - my-network
  db:
    image: postgres:alpine
    ports:
      - "64321:5432"
    networks:
      - my-network 
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

networks:
  my-network:
    driver: bridge